### ISSUE TITLE
Add audio playing to API

### ISSUE THREAD

**Issue by 2mac** [erikd/libsndfile#111]
There is an example program for playing audio on various platforms. I think it would be a nice addition to take that functionality and make it its own function

    sf_play (SNDFILE *sndfile, int start_frame, int end_frame);

or possibly accept timestamps, etc.

**Comment by erikd** [comment]
Sorry, I don't think this is a good fit for the library. The main reason is that libsndfile is a file format reader and writer and writing audio data is to an audio device does not fit with that.

On top of that there are already a number of general audio device I/O libraries like `portaudio`, `libao`, `libjack`, `SFML`, `OpenAL` and possibly others.

The `sndfile-play` was originally written as an example program that I used for testing. Initially it only supported Linux. Since then, many others have added support for other platforms.
