### ISSUE TITLE
Definite integer length

### ISSUE THREAD

**Issue by 2mac** [erikd/libsndfile#112]
`short` and `int` do not have definite sizes in the standard, only minimum ones, and on some systems `short` and `int` can actually be the same size.

Could functions like `sf_read_int8`, `sf_writef_16`, etc. be added for known depth?

**Comment by 2mac** [comment]
This of course using the types from `stdint.h`

**Comment by erikd** [comment]
libsndfile was first released over 15 years ago, before `<sndint.h>` was even part pf the standard. Furthermore, on Windows, `<stdint.h>` was not part of the MSVC under very recently.

Finally, in all the years libsndfile has been out I have yet to hear of a single platform where somewone wanted to use libsndfile but couldn't because sizes of `short` and `int` were incorrect.
