### ISSUE TITLE
Make Automake buildsystem completely non-recursive

### ISSUE THREAD

**Issue by SoapGentoo** [erikd/libsndfile#286]
Hi @erikd 
I would like to propose a (probably very invasive) change for the build system. Currently the build system is a standard recursive Make based system. One massive drawback of this is that parallelization only happens on a per-directory level, as directory traversals have to be serialised. This is 1) slow and 2) allows only for limited concurrency. The only real solution to this problem is a non-recursive Make based system, as you have also blogged about (http://www.mega-nerd.com/erikd/Blog/CodeHacking/nonrecursive_automake.html). I have two potential ways to go about this:

1. One single `Makefile.am` in the root declaring everything. This is extremely invasive, yet I consider this the cleanest. systemd does this and I consider it the globally optimal solution personally.
2. Keep the `Makefile.am`'s as they are currently, but rename them to `module.mk` or something else and include them from the root `Makefile.am`. This is less invasive, but always requires mentally thinking in terms relative to the root source dir and using the weird relative syntax which few people know. GNU Octave does this (https://hg.savannah.gnu.org/hgweb/octave/file/05bbca224a14/src/module.mk).

Are you up for a conversion? Which approach would you prefer?

**Comment by erikd** [comment]
Slow? On my laptop after a `make clean`, `make all check` takes 58 seconds. After a `make distclean`, a `./autogen.sh && ./configure && make clean all check` takes 1m14s. In what universe is that slow?

**Comment by evpobr** [comment]
@SoapGentoo 
>> Currently the build system is a standard recursive Make based system.
Not exactly (i guess). `libgsm`, `libg72x` and `libalac` are built from src/Makefile.am.

@erikd, i guess it can be **even** faster if you run make with `-j` option. Why loose chance to speedup build even more?

**Comment by erikd** [comment]
I made part of the build system non-recursive some time ago, because with the `src/` tree that was genuinely advantageous. I have no objection to taking that further but for me the pay off was insufficient. 

One important requirement is that changes don't prevent me from doing my normal debugging. For instance when I was debugging the recent RF64 header issues I had a tiny shell script:
```
#!/bin/bash -eu
(cd src && make)
(cd tests && make header_test)
tests/header_test rf64
```

With a fully non-recursive automake build system I should be able to make changes to `src/rf64.c` and simply do:
```
make tests/header_test && tests/header_test rf64
```
and that should build everything that needs to be built and run the new test binary.

So, I think option 1) One single Makefile.am in the root declaring everything is probably best, but I really hope that single file doesn't end up much bigger than the sum of the current `Makefile.am`s.

**Comment by SoapGentoo** [comment]
I see your point, and yes, the returns likely won't be massive (maybe lucky if you can shave 10-15s off the total). If you dont want me doing this, close it an we leave it.

**Comment by erikd** [comment]
With the proviso that debugging is as easy as it was before, I am happy for you to do this.

**Comment by erikd** [comment]
I think this is done now. Closing.
