### ISSUE TITLE
Not able to build for android on ubuntu

### ISSUE THREAD

**Issue by hitendrasinh2015** [erikd/libsndfile#323]
Hi,
I am trying to build .so file for android project. I tried to build it on linux machine using android ndk. Please check the log in below text file.
https://drive.google.com/open?id=0B3hSlw1AYdKYaXBFNk9CWHhzbzQ

Can anybody please help me find the issue? and yes in which directory i can see .so file?

**Comment by hitendrasinh2015** [comment]
@erikd , can you please tell me what is wrong here?

**Comment by Ghabry** [comment]
The build was succesful, I don't see an error message?
You didn't run "make install", run configure with argument "--prefix=PATH_TO_INSTALL_TO", than the lib appears in PATH_TO_INSTALL/lib after "make install"

**Comment by hitendrasinh2015** [comment]
@Ghabry thanks a lot. I am able to identify the .so file now. I have another question. In android i have three types of libs armeabi, armeabi-v7a and x86. So how can i build this three different type of .so files ?

**Comment by Ghabry** [comment]
This works the same for all libraries you crosscompile: You have to pass the correct arguments to configure. Take a look in that android-configure.sh script, you have to modify it.

The relevant part is the SYSROOT.
For armeabi-v7a you use the same SYSROOT as for armeabi (which is the default in that script) and add "-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3" to CFLAGS and CXXFLAGS.

For x86 and mips you have to specify the correct triplet and the correct folder:
The triplet is passed via ANDROID_TARGET.

x86-triplet: i686-linux-android
mips triplet: mipsel-linux-android

You pass this via "ANDROID_TARGET=TARGET_HERE ./android-configure.sh ....."

ANDROID_PREFIX and SYSROOT are hardcoded in the script. You have to change them in such a way that the folder points to the correct sysroot. Can't help you with this because I don't have the NDK installed, but the parts that must be changed are "arm-linux-androideabi" and "arch-arm". Take a look in the NDK folder to find the correct folder names.

Important:
- Run "make clean" before configure.
- Use different --prefix for all of them otherwise they overwrite each other when you "make install".

**Comment by hitendrasinh2015** [comment]
@Ghabry , thanks. I will try and let you know.

**Comment by erikd** [comment]
Can this be closed?

**Comment by hitendrasinh2015** [comment]
Yes, please

**Comment by LightSun** [comment]
@Ghabry Could you tell me how to build for arm64?
