### ISSUE TITLE
Binaries of Debian and other Unix distros.

### ISSUE THREAD

**Issue by fredvs** [erikd/libsndfile#458]
Hello.

By curiosity, is it the libsndfile-staff who compiles and gives the binary to the distros or is it compiled by the distros their-self?

Is it possible to know what parameters was used to compile the libsndfile.so of the distro (what compiler,... etc) ?

Thanks.

Fre;D

**Comment by erikd** [comment]
> is it compiled by the distros their-self?

This!

I barely have enough spare time or motivation to respond to issues and merge PRs let alone compile libsndfile for all the different Linux distros.

I release a WIndows binary (cross compilled on a Linux machine) for libsndfile because doing so is many orders of magnitude easier than supporting actually building on Windows.

**Comment by fredvs** [comment]
@erikd 

Ok, thanks.
But is possible to know how they did compile the binary they give?
If no, what do you think to add in `sf_version_string` (or a other method) some more infos, like the compiler and the parameters used ?

Thanks.

**Comment by erikd** [comment]
> But is possible to know how they did compile the binary they give?

Distribution specific.

> If no, what do you think to add in sf_version_string (or a other method) some more infos, like the compiler and the libsndfile parameters used ?

I think that is a bad idea.

> Ha, so it is possible, do you do it with wine + gcc.exe or with Linux gcc + tool-chain-cross-compile ?

Yes it works and it works very well.

**Comment by fredvs** [comment]
Hello Erik.

OK, thanks.

Fre;D
