### ISSUE TITLE
Extend support for XMA (high def WMA) and add ATRAC (high def Sony) formats

### ISSUE THREAD

**Issue by guilt** [erikd/libsndfile#467]
Hi,

It is a very useful way for people to use sndfile, esp when converting between sound formats and/or loading these formats in video games.

Hence this request to support this WMA extension and Sony's lossless high def format.

**Comment by erikd** [comment]
libsndfile does not yet support WMA which would probably be a first step towards supporting XMA.

However, WMA is difficult to support because Microsoft releases zero information about how to encode and decode this format. Furthermore, even if if they did release specs it is unlikely I would have time to add support from the specs. Its a similar story for this Sony format.

However, libsndfile does support the FLAC lossless format which is a royalty and patent free codec with an Open Source reference implementation.

Support for the [Opus format](https://en.wikipedia.org/wiki/Opus_(audio_format))(again royalty and patent free with an Open Source reference implementation) has recently been added and is supported on all platforms.

**Comment by guilt** [comment]
Okay. I saw it supported in ffmpeg and hence asked. Closing.
