### ISSUE TITLE
Libsndfile for Scilab 6.0.2

### ISSUE THREAD

**Issue by ImNanou** [erikd/libsndfile#501]
Hello,

I have for project to use libsndfile with Scilab 6.0.2 (it's a mathematic software such as Matlab and Octave). The probleme is that I'm a little bit loss..

At first I just want to use the playing audio system in a way to read my file, just like the case with your demo program for Octave. 

If someone could help me, it will be awesome.

**Comment by erikd** [comment]
Making Scilab use libsndfile is not a libsndfile issue.

The reason there is Octave support is because I used to be a frequent user of Octave. I have never used Scilab.

From my experience with adding Otcave/libsndfuile support I am pretty certain that it would be far more difficult for a libsndfile developer to add this support to Scilab than it would be for a Scilab developer. I therefore suggest you raise this issue with the Scilab developers.

**Comment by Nelson-numerical-software** [comment]
see http://forge.scilab.org/index.php/p/sndfile-toolbox/
And more here: https://nelson-numerical-software.github.io/nelson-website/help/en_US/chapter_audio.html

**Comment by ImNanou** [comment]
Thanks for reply. I already see this program but it doesn’t work for Scilab 6.X.X just 5.4.

I will do my best to do it then.

De : Allan CORNET<mailto:notifications@github.com>
Envoyé le :vendredi 6 décembre 2019 07:13
À : erikd/libsndfile<mailto:libsndfile@noreply.github.com>
Cc : ImNanou<mailto:maxime-17200@hotmail.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [erikd/libsndfile] Libsndfile for Scilab 6.0.2 (#501)


see http://forge.scilab.org/index.php/p/sndfile-toolbox/
And more here: https://nelson-numerical-software.github.io/nelson-website/help/en_US/chapter_audio.html
