### ISSUE TITLE
ogg_opus.c issue with opus header files

### ISSUE THREAD

**Issue by rlyon01** [erikd/libsndfile#506]
Currently building sndfile.dll from github repsitory using cmake 3.16.3 and VS2019 on windows 10. 

Opus 1.3.1 and later header files are located in `opus/include`, not `opus/include/opus`. In the source file ogg_opus.c lines 165 and 166

```
#include <opus/opus.h>
#include <opus/opus_multistream.h>
```

need to be modified to 

```
#include <opus.h>
#include <opus_multistream.h>
```

Forgot to mention this before.

**Comment by erikd** [comment]
I think that is actually a bug in the CMake build rather than in the C sources.

@evpobr ?

**Comment by evpobr** [comment]
@erikd, we have bug:

In `opus.pc.in`:

```
Cflags: -I${includedir}/opus
```

I think this worked before, because other `.pc` modules added `${includedir}` anyway.

**Comment by erikd** [comment]
PR?

**Comment by evpobr** [comment]
Ok.

**Comment by erikd** [comment]
Looking at this again with fresh eyes this morning I am confused. Is `opus.pc.in` in the libsndile repo?

**Comment by evpobr** [comment]
No, from Opus repo.

**Comment by erikd** [comment]
Ok the opus library provides that file and it is actually incorrect. I have raised an issue: https://github.com/xiph/opus/issues/164

In the meantime, libsndfile file should use `<opus/header.h>` even if it has t massage/correct the of `Cflags` provided by `pkh-config` (used to do this for FLAC). 

I am happy to do the autotools fix if someone else can do the fix for Cmake.

**Comment by jmvalin** [comment]
Actually, Opus header files are meant to be included as <header.h> and not <opus/header.h> and using the latter can actually break if Opus is installed in a different place, e.g. the headers could very well be in /usr/local/include/opus-1.3.1/

To avoid naming clashes, all Opus headers start with the "opus" prefix. We can debate the merits of how Opus handles headers (the original reason was to make really sure the build couldn't use installed headers), but in the end that's how they've been handled for years and changing that would break existing builds for many people. Considering the risk of clash is really small, please consider just #include <opus.h>

**Comment by evpobr** [comment]
Fixed for CMake too.

**Comment by FiniteReality** [comment]
It appears that while the appropriate fix has been added to xiph/opus, `ogg_opus.c` hasn't actually been updated to reflect that - it still searches for headers in `<opus/opus.h>` rather than just including `<opus.h>`. Is there a branch I'm missing that has these changes, or were they simply missed?
