### ISSUE TITLE
Text strings encoding

### ISSUE THREAD

**Issue by vokimon** [erikd/libsndfile#67]
API documentation does not states on how to deal with non-ascii text in metadata strings such as title, author...

While Vorbis Comments (ogg, speex, flac) are utf-8, ID3v1 is latin1 and ID3v2 might be latin1, utf8, ucs or utf16-LE depending on a flag. I have no idea on which encoding uses metadata in other formats such as WAV or AIFF.

Anyway libsndfile should provide either:
- text strings in a common universal text encoding such as utf-8, or
- means to know the text encoding to deal with.

Could we asume the former? Is there any means for the later?

**Comment by erikd** [comment]
@vokimon Please check out the above commit and let me know if its up to scratch.

**Comment by erikd** [comment]
Thanks @vokimon. I'll mark this as fixed.

**Comment by camlorn** [comment]
I think you can kill `sf_wchar_open` by just always decoding from UTF8; see [MultiByteToWideChar](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072%28v=vs.85%29.aspx).
This would give a uniform interface across all platforms and mirrors the approach I'm taking in my software: since every other platform is already UTF8, define as part of the API that incoming strings need to be UTF8 and decode as appropriate.
Just a thought, but I think this might be better than a windows-specific function, it's compatible with ascii so it won't break any existing software, and it should be an easy patch.
