### ISSUE TITLE
can't decode raw IMA ADPCM with sf_open_virtual

### ISSUE THREAD

**Issue by gchilds** [erikd/libsndfile#95]
When I use `sf_open_virtual` to open a raw ima stream
`info.format = SF_FORMAT_RAW | SF_FORMAT_IMA_ADPCM;`

I get the following error:

    Error. Bad format field in SF_INFO struct when openning a RAW file for read.

However, `SF_FORMAT_RAW | SF_FORMAT_VOX_ADPCM` succeeds.

Shouldn't containerless ima work?

Ok, I can see it's not supported in raw, but it doesn't look hard to hook up... I think my biggest hurdle would be getting autoconf to generate a makefile on my mac. That and having to give up using the package manager versions of the lib.

Nice work, btw. Thanks.

**Comment by erikd** [comment]
A format of `SF_FORMAT_RAW | SF_FORMAT_IMA_ADPCM` can never work because, `SF_FORMAT_IMA_ADPCM` has a variable block size and that block size must be stored somewhere. For `SF_FORMAT_WAV | SF_FORMAT_IMA_ADPCM` and `SF_FORMAT_AIFF | SF_FORMAT_IMA_ADPCM`, the block size of stored in the WAV/AIFF header.

`SF_FORMAT_RAW | SF_FORMAT_VOX_ADPCM` works because `SF_FORMAT_VOX_ADPCM` has a constant block size.

If you're happy with this explanation, please close this issue.

**Comment by gchilds** [comment]
I thought `SF_FORMAT_IMA_ADPCM` _was_ constant blocksize as `blocksize = 34*info.channels`. Although maybe I've got my ADPCMs mixed up? I'm thinking of the apple version.

**Comment by erikd** [comment]
Acutally you may be correct for AIFF's IMA_ADPCM, but for WAV, the block size is variable.

**Comment by gchilds** [comment]
Ah, ok. I don't suppose you'd be interested in a PR for a raw compatible `SF_FORMAT_AIFF_IMA_ADPCM`?

**Comment by gchilds** [comment]
`SF_INFO` acts as the raw stream's missing header - maybe I could add enough extra fields there to allow parsing of both wav and AIFF style IMA_ADPCM.

**Comment by erikd** [comment]
> Ah, ok. I don't suppose you'd be interested in a PR for a raw compatible SF_FORMAT_AIFF_IMA_ADPCM?

Nope. I see headerless formats as as a mistake. A valid WAV or AIFF file header can be as little as 44 bytes and those 44 bytes bytes tell you everything you need to know to decode and play the file.

I added the ability to read/write raw header-less files because there were a small number of formats where that was the default. I am not interesting in propagating the *mistake* of header-less files.

> SF_INFO acts as the raw stream's missing header - maybe I could add enough extra fields there to allow parsing of both wav and AIFF style IMA_ADPCM. 

The SF_INFO struct is part of the API. The API has changed in over 10 years and sorry, I'm not going to change it for this hack.

**Comment by gchilds** [comment]
I thought `libsndfile` might be useful for streaming audio, but I guess not because the codecs are gratuitously coupled to a few file containers.

My mistake, it's all in the name really. I now realise I'm looking for `libsndcodec`.
